name: Complex
on:
  push:
    branches: ["master"]
jobs:
  job1:
    name: Run on ubuntu1
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date
  job2:
    name: Run on windows
    runs-on: windows-latest
    steps:
      - run: date
  job3:
    name: Run on mac
    runs-on: macos-latest
    steps:
      - run: date
  job4:
    needs: [job1, job2, job3]
    name: Run on ubuntu2
    runs-on: ubuntu-latest
    steps:
      - run: date
